### ISSUE TITLE
Graph Panel > Multiple Selects

### ISSUE THREAD

**Issue by joemoe** [raintank/crate-datasource#13]
Multiple Selects don't seem to work:

I have a Graph Panel with multiple Selects. It only visualizes the first Select.
<img width="1197" alt="bildschirmfoto 2016-09-23 um 10 31 50" src="https://cloud.githubusercontent.com/assets/68620/18779478/819b2508-8179-11e6-9008-977e58f5d37f.png">

When I hide the first, it visualizes the second:
<img width="1174" alt="bildschirmfoto 2016-09-23 um 10 31 58" src="https://cloud.githubusercontent.com/assets/68620/18779496/8c1329cc-8179-11e6-99a6-b99e92568af7.png">

Am I doing something wrong?

**Comment by alexanderzobnin** [comment]
Confirmed, this is really a bug.

**Comment by alexanderzobnin** [comment]
Try to build from `fix-multiple_selects` branch.

**Comment by joemoe** [comment]
tested it, and it seems to work fine.

**Comment by alexanderzobnin** [comment]
Ok, I'll add more tests and then merge it into master.

**Comment by joemoe** [comment]
hi @alexanderzobnin were you able to merge it to master?

**Comment by alexanderzobnin** [comment]
Yes, just merged.

**Comment by joemoe** [comment]
this works now.
