### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by joemoe** [raintank/crate-datasource#15]
@alexanderzobnin same with the table. should this work already? because it seems like there's only some demo data in it.

**Comment by alexanderzobnin** [comment]
Can you describe requirements for table panel?

**Comment by joemoe** [comment]
i think it would make sense to have:

* time series to row
* time series to column
* time series to aggregations

annotations might also be nice, but it's only a nice to have. JSON Data is not necessary right now.

**Comment by alexanderzobnin** [comment]
@joemoe it works for me. These modes for table panel uses timeseries data, so no additional implementation is needed.
