### ISSUE TITLE
plotting raw value tries to GROUP BY

### ISSUE THREAD

**Issue by jodok** [raintank/crate-datasource#19]
i'm trying to plot a single value without aggregation
<img width="797" alt="raw" src="https://cloud.githubusercontent.com/assets/158125/20456324/032d238c-ae75-11e6-9fd7-88d03534a486.png">

and the datasource is being queried like that:

```
{"stmt":"SELECT count(*) FROM \"mruepp\".\"missionj\" WHERE timestamp >= ? AND timestamp <= ? AND payload['fieldname'] = 'Weight PCR_Line01' GROUP BY , payload['value']","args":[1479547509769,1479569109770]}
```

but it should be:

```
{"stmt":"SELECT payload['value'] FROM \"mruepp\".\"missionj\" WHERE timestamp >= ? AND timestamp <= ? AND payload['fieldname'] = 'Weight PCR_Line01'","args":[1479547509769,1479569109770]}
```

**Comment by jodok** [comment]
ok, could debug this further - problem occurs if the `Group By Time Interval` is set to `Auto`

**Comment by alexanderzobnin** [comment]
It's because we invoke `SELECT count(*)` query first to determine amount of points to return and select proper Group By Time Interval. See #11. Can you show second query (after SELECT count(*))?

**Comment by joemoe** [comment]
it seems like there is a new problem. auto does now a query crate can't handle anymore.
<img width="645" alt="" src="https://cloud.githubusercontent.com/assets/68620/20687655/a75d1dd2-b5bd-11e6-9e94-539792097f4d.png">

what do mean by show second query?

**Comment by joemoe** [comment]
hm, it worked now. there seems to be some edge case.

**Comment by joemoe** [comment]
can't reproduce it anymore.

**Comment by joemoe** [comment]
is this still an issue for you @jodok?

**Comment by jodok** [comment]
yes, still an issue. is there a way i can help to debug?

**Comment by joemoe** [comment]
@alexanderzobnin we narrowed it down to having no `alias` set.
