### ISSUE TITLE
if one field as custom SQL, this is shown on the second line as well

### ISSUE THREAD

**Issue by jodok** [raintank/crate-datasource#20]
collapsed field shows the same:
<img width="1252" alt="sql1" src="https://cloud.githubusercontent.com/assets/158125/20456482/adb02776-ae77-11e6-9ec5-3543b7f051e6.png">
uncollapsed field:
<img width="1157" alt="sql2" src="https://cloud.githubusercontent.com/assets/158125/20456485/b630266c-ae77-11e6-9eb4-36220c1f4f82.png">

i'd expect to see the actual SQL

**Comment by alexanderzobnin** [comment]
Can you show first query (`A`)? I can't see difference on these pictures.

**Comment by jodok** [comment]
yes, that's the problem - it's somehow always the same. but i think i could debug it further.
the problem is that the collapsed view of a custom sql query doesn't show the query i entered in the custom SQL query ("toggle edit")
custom query:
<img width="1084" alt="sql" src="https://cloud.githubusercontent.com/assets/158125/20606990/1b5039e6-b275-11e6-9f1b-4265d6be986b.png">

collapsed view:
<img width="1038" alt="collapsed" src="https://cloud.githubusercontent.com/assets/158125/20606994/2158ff8a-b275-11e6-951f-033202a90c2a.png">

**Comment by alexanderzobnin** [comment]
Aha, seems, that's a reason.

**Comment by joemoe** [comment]
this works for me now. can you confirm, @jodok ?

**Comment by jodok** [comment]
works for me.
