### ISSUE TITLE
Custom text in legend

### ISSUE THREAD

**Issue by joemoe** [raintank/crate-datasource#22]
Is there a way to modify the legend text.
We have now 10 Lines where each says `arbitrary(payload['value'])`, which looks odd.

We'd like to:

* make showing aggregation type custom.
* being able to run a regular expression replacement over the labels.

**Comment by jodok** [comment]
i think this is called alias?

**Comment by alexanderzobnin** [comment]
Yes, I think I can add Alias field for each SELECT.

**Comment by joemoe** [comment]
@alexanderzobnin this seems to work fine. just tested it.

**Comment by alexanderzobnin** [comment]
@joemoe do you need this: ?
- make showing aggregation type custom.
- being able to run a regular expression replacement over the labels.
