### ISSUE TITLE
Repeat Panels

### ISSUE THREAD

**Issue by joemoe** [raintank/crate-datasource#23]
We want to have a repeated panels view.
It works that the panels are repeated. The problem is that it doesn't push the queries through.

So we configured the repeat by an var:

<img width="456" alt="grafana-repeat" src="https://cloud.githubusercontent.com/assets/68620/20478594/0b183660-afdb-11e6-98bd-b8a92ae3de9c.png">

The panel is correctly shown with the correct title.

<img width="203" alt="grafana-repeat-title" src="https://cloud.githubusercontent.com/assets/68620/20478605/185ee1c0-afdb-11e6-8ed5-47076b61c28d.png">

But the query connects all selected values.

<img width="182" alt="grafana-repeat-query" src="https://cloud.githubusercontent.com/assets/68620/20478609/22962540-afdb-11e6-8a11-ea85bd6e24ec.png">

It is built like this:

<img width="332" alt="grafana-repeat-query-builder" src="https://cloud.githubusercontent.com/assets/68620/20478644/3efa86f4-afdb-11e6-8f3f-e3e162284ef1.png">

**Comment by joemoe** [comment]
it seems to work now better. 

but there are still some issues:

* i get an error i can't move away

<img width="294" alt="bildschirmfoto 2016-11-28 um 23 06 54" src="https://cloud.githubusercontent.com/assets/68620/20688073/7df978e4-b5bf-11e6-8d54-d86742863f87.png">

* and although it seems to works fine it doesn't size the graphs well, when setting no min span. i mean this could be the default behaviour. i still don't like it. :)
<img width="1280" alt="bildschirmfoto 2016-11-28 um 23 07 56" src="https://cloud.githubusercontent.com/assets/68620/20688126/c44da5fe-b5bf-11e6-9f11-e50e5c54d65a.png">


* also i had to refresh everything like 4 times to get it properly running

**Comment by alexanderzobnin** [comment]
@joemoe do you see any errors in JS console (in developer tools)?

**Comment by joemoe** [comment]
@alexanderzobnin this works. i had an error in the configuration.
there's just one thing that as i think is `grafana`specific. so when i want to change to look of all the repeated panels, i have to touch all of them. in my opinion i should just change one, the first. but i guess this is a different topic.

**Comment by alexanderzobnin** [comment]
@joemoe you can do it by changing first panel only, but it may require page reload. I's grafana behaviour.
