### ISSUE TITLE
modifying group by column values

### ISSUE THREAD

**Issue by joemoe** [raintank/crate-datasource#27]
when we do a group by a field that has longer values we totally clutter the legend.
it would be cool to have there also the possibility to add a regexp or whatever.

we often work with iot data and they use so called topics.
topics often look like this `/crate/download/server/tar.gz/weekly`

**Comment by alexanderzobnin** [comment]
Put regex in `AS` field for group by to extract part of column value. You can also use capture groups.

<img width="1280" alt="screen shot 2016-12-04 at 21 31 07" src="https://cloud.githubusercontent.com/assets/4932851/20868295/4de0bc90-ba69-11e6-9d59-95811e1bbdf6.png">

**Comment by joemoe** [comment]
@alexanderzobnin this works fine now. i'm just not sure if rows that are regexed to the same value should be combined.
e.g. when you have `.{1-3}` and you have two different values like `abcd` and `abce` in my opinion  they shouldn't be aggregated to the same line.
what do you think @jodok?

**Comment by alexanderzobnin** [comment]
@joemoe you're right, I thought about that. I'll check this behaviour.
