### ISSUE TITLE
quote column names

### ISSUE THREAD

**Issue by joemoe** [raintank/crate-datasource#28]
when working with camelcase column names we need to quote them, because otherwise they will be changed to lower case which breaks the query.

**Comment by jodok** [comment]
<img width="749" alt="screenshot 2016-12-01 09 38 38" src="https://cloud.githubusercontent.com/assets/158125/20787048/1d6b6e1e-b7aa-11e6-894e-f4885ece7663.png">
<img width="716" alt="screenshot 2016-12-01 09 38 48" src="https://cloud.githubusercontent.com/assets/158125/20787049/1d6b9862-b7aa-11e6-90b9-651b5cc7bfcd.png">
