### ISSUE TITLE
404 error upon installing new crate-datasource

### ISSUE THREAD

**Issue by Node0** [raintank/crate-datasource#3]
Logged out of Grafana, then:

ssh into server, then:
#### > exit 

Logged back in to grafana.
Went to  (on left sidebar):
Datasources --> Add Datasource --> select 'Crate'

Then saw this in notification popup:

Plugin Error
Error: XHR error (404 Not Found) loading
http://foo.com/public/plugins/crate-datasource/module.js?bust=1463444679992
Error loading http://foo.com/public/plugins/crate-datasource/module.js

Am currently attempting to narrow down where the plugin expects to find its files.

i.e. (see attached)
![grafana_error_upon_selecting_crate_datasource](https://cloud.githubusercontent.com/assets/2231752/15308336/f9dfdfd0-1b90-11e6-861c-17714a831334.jpg)

**Comment by Node0** [comment]
root@sage:/usr/share/grafana# find . | grep -Pi "crate"
./data/plugins/crate-datasource
./data/plugins/crate-datasource/package.json
./data/plugins/crate-datasource/.gitignore
./data/plugins/crate-datasource/plugin.json
./data/plugins/crate-datasource/Gruntfile.js
./data/plugins/crate-datasource/.jscsrc
./data/plugins/crate-datasource/README.md
./data/plugins/crate-datasource/src
./data/plugins/crate-datasource/src/response_handler.js
./data/plugins/crate-datasource/src/module.js
./data/plugins/crate-datasource/src/partials
./data/plugins/crate-datasource/src/partials/query.editor.html
./data/plugins/crate-datasource/src/partials/config.html
./data/plugins/crate-datasource/src/partials/query.options.html
./data/plugins/crate-datasource/src/query_builder.js
./data/plugins/crate-datasource/src/img
./data/plugins/crate-datasource/src/img/crate_logo.png
./data/plugins/crate-datasource/src/query_ctrl.js
./data/plugins/crate-datasource/src/datasource.js
./data/plugins/crate-datasource/.jshintrc

##### > root@foo:/usr/share/grafana# ln -s data/plugins/crate-datasource public/app/plugins/datasource/crate-datasource

Nope , that doesn't resolve the issue, and neither does actually making a copy of the contents
of /data/plugins/crate-datasource/src/ --> public/app/plugins/datasource/crate-datasource

Some help at this juncture would be quite appreciated.

**Comment by alexanderzobnin** [comment]
Hi, @Node0. Try to remove /data/plugins/crate-datasource and clone latest version of crate-datasource here:
```
cd data/plugins
git clone https://github.com/raintank/crate-datasource.git
service grafana-server restart
```

**Comment by Node0** [comment]
A bunch of commits have occurred, removing plugin, and starting again fresh.
Hopefully this bug has also been quashed.

**Comment by Node0** [comment]
Indeed, I've tried that, I've also tried removing the crate-datasource from __all__ locations i.e. 
1.) /usr/share/grafana/public/app/plugins/datasource/crate-datasource,
2.) /usr/share/grafana/data/plugins/crate-datasource,
3.) /var/lib/grafana/plugins/crate-datasource/
  
  
It's that last one: /var/lib/grafana/plugins/crate-datasource/   which was key... specifically when I install the plugin via grafana-cli (or even when I git clone into either 1 or 2 ) nothing helped, not even adding the /dist directory under the 'crate-datasource' to 1 or 2 above.

What DOES seem to work? Well... I start a new version upgrade by:

A.) # > `grafana-cli plugins uninstall crate-datasource`
B.) # > `grafana-cli plugins remove crate-datasource`
C.) # > `rm -rf /usr/share/grafana/public/app/plugins/datasource/crate-datasource /usr/share/grafana/data/plugins/crate-datasource /var/lib/grafana/plugins/crate-datasource/; `
D.) # > `grafana-cli plugins install crate-datasource`
E.) # > `mkdir /var/lib/grafana/tempclone`
F.) # > `cd /var/lib/grafana/tempclone`
G.) # > `git clone https://github.com/raintank/crate-datasource.git`
H.) # > `cp -r /var/lib/grafana/tempclone/crate-datasource/dist /var/lib/grafana/plugins/crate-datasource/`
I.) #> `cd ..`
J.) # > `rm -rf /var/lib/grafana/tempclone`
K.) # > `chown -R grafana:grafana /var/lib/grafana`

Hmmm, I should turn this into a shell script, because it's tedious...
Done, [here's the gist](https://gist.github.com/Node0/ea2d58e7f6ff597e1dfa9bd2f6cf1c55)

So I've solved the problem for my own needs, mmmmm I should probably do it in NodeJS just because, but no time atm.

It would be nice if I didn't have to write a script to do this but at this point I've solved the problem for me, it would be nice to get it solved by default (for other users).

I've tested this and it works on ubuntu 14.04, which is amazing given how it basically nukes everything and does a fresh install + git clone.

**Comment by Node0** [comment]
If you add the shell script as a post install hook for at least ubuntu systems (haven't tested this on centos) you might be able to just close the issue. Well either that or determine why grafana-cli plugins install crate-datasource doesn't result in a working installation of crate-datasource.

**Comment by alexanderzobnin** [comment]
I just not sure that grafana-cli points to latest version of plugin. I'll try to fix it tomorrow.

**Comment by Node0** [comment]
In the non-working grafana-cli plugin installs, it looks like the 'dist' directory was not present in /var/lib/grafana/plugins/crate-datasource/

All my shell script does is start from a clean state (wipes the installed crate-datasource, and removes its current directories) then installs the crate datasource via grafana-cli then does the manual git clone to a temp directory, and then copies the 'dist' directory to the right place, and chowns the /var/lib/grafana directory so all the files belong to the grafana user.  I imagine either the 'dist' directory is not being copied over in the grafana-cli install steps (or is not present in the install package grafana-cli fetches) or it is present in the package but not copied to the right place.

It seems like a simple enough fix. I just needed a quick fix until it gets resolved properly.
