### ISSUE TITLE
separate graphs by grouped by column in custom query

### ISSUE THREAD

**Issue by joemoe** [raintank/crate-datasource#30]
when we do a custom query and want to have graphs for every group by value it doesn't seem possible at the moment. 
is there a way to achieve this?

**Comment by jodok** [comment]
![screenshot 2016-12-01 09 56 33](https://cloud.githubusercontent.com/assets/158125/20787547/ac9a4450-b7ac-11e6-818b-d717e499c206.png)

**Comment by alexanderzobnin** [comment]
It isn't so easy - we should parse query and find GROUP BY clause and its columns, but I think it's possible.

**Comment by joemoe** [comment]
ok, let's leave it for now, we should keep this in mind.
can't you use the number of returned values.
no1: timestamp, x val
no2: value, y val
no3: group
or does this destroy something else?

**Comment by alexanderzobnin** [comment]
It makes sense to use rest values from each row as GROUP BY column values. I'll do it.
