### ISSUE TITLE
Empty group by

### ISSUE THREAD

**Issue by joemoe** [raintank/crate-datasource#31]
when we select multiple values without using a `group by` it only shows one.

empty `group by`s seem to make problems.
can't you just leave the `group by` condition aside when there's no field to group by.

<img width="349" alt="bildschirmfoto 2016-12-02 um 10 31 45" src="https://cloud.githubusercontent.com/assets/68620/20829102/e5a6a13e-b87a-11e6-9673-2cb2c3ed8412.png">
<img width="379" alt="bildschirmfoto 2016-12-02 um 10 31 32" src="https://cloud.githubusercontent.com/assets/68620/20829101/e5a3d512-b87a-11e6-88a8-51cf2751111d.png">

**Comment by jodok** [comment]
the graph is now correctly displayed. but it seems the axes are displayed with the wrong scale.
if i display only one graph:
<img width="543" alt="1" src="https://cloud.githubusercontent.com/assets/158125/24084735/38e1532a-0cf0-11e7-9fc1-321313391306.png">

if i select the second graph, showing load/2 the numbers on the y-axes are to high.
<img width="523" alt="2" src="https://cloud.githubusercontent.com/assets/158125/24084743/565ba05e-0cf0-11e7-8e2d-962cf1c30a97.png">
