### ISSUE TITLE
Allow non-numeric data in Table panel

### ISSUE THREAD

**Issue by buom** [raintank/crate-datasource#32]
Please help me how to display data in table_pannel (http://docs.grafana.org/reference/table_panel/) correctly

In Grafana:
query: 
![image](https://cloud.githubusercontent.com/assets/39004/21292667/5efd8950-c53f-11e6-920e-ddc25b0f8855.png)

![image](https://cloud.githubusercontent.com/assets/39004/21292721/afe969a0-c540-11e6-8f33-ad54004c2cc7.png)

result:
![image](https://cloud.githubusercontent.com/assets/39004/21292673/9bc947ac-c53f-11e6-83e1-b57d40840beb.png)

In Create:
![image](https://cloud.githubusercontent.com/assets/39004/21292711/4c26183c-c540-11e6-9077-5172f27446ab.png)

**Comment by alexanderzobnin** [comment]
We need to implement table mode for queries, otherwise grafana considers that data is time series and has numeric values.

**Comment by alexanderzobnin** [comment]
@buom closed by your PR.
