### ISSUE TITLE
Alias at `GROUP BY` field is not used

### ISSUE THREAD

**Issue by mikethebeer** [raintank/crate-datasource#35]
If an alias is set to the `group by` field, it will be not used in the SQL request.

![grafana-metrics](https://cloud.githubusercontent.com/assets/6863216/22252466/948a2cc8-e24e-11e6-8b93-dba08f0d4345.PNG)

Will be generated in:

```sql
SELECT date_trunc('second', current_timestamp) as time, count(*) AS "metric", geohash(coordinates)
FROM "sys"."summits"
WHERE current_timestamp >= ? and current_timestamp <= ?
GROUP BY time, geohash(coordinates)
ORDER BY time, geohash(coordinates) ASC
```

**Comment by alexanderzobnin** [comment]
Sorry for confused option. Group By alias works when grafana processes response. It just allows to extract part of returned group by column value using regex:

![screenshot from 2017-03-19 21 27 00](https://cloud.githubusercontent.com/assets/4932851/24083582/d668c6ba-0cea-11e7-861a-5562724d6b0f.png)

Original tag name was `house_1`
