### ISSUE TITLE
value discovery for where filter uses `$timeFilter` but does not resolve it

### ISSUE THREAD

**Issue by jodok** [raintank/crate-datasource#38]
when building the WHERE clause in the filter the query builder uses the `$timeFilter` variable but doesn't substitute it.
![screenshot 2017-03-09 00 15 50](https://cloud.githubusercontent.com/assets/158125/23728594/f43a8790-045d-11e7-816b-9537a556e588.png)

**Comment by alexanderzobnin** [comment]
Fixed by dd342ad5bae2ed8bfc3f9fb4eccd63c645f3f897
