### ISSUE TITLE
scopedVars is undefined

### ISSUE THREAD

**Issue by sybrandy** [raintank/crate-datasource#41]
Hello,

I'm getting that error after upgrading the datasource today to version 0.5.0.  Brief stack trace below:

datasource.js?bust=<num>:249:68
datasource.js?bust=<num>:123:38

Tried this with both a pie chart and a graph.  Simple query:

    select ts as time, count(state), state
    from "proj"."states"
    where ts >= ? and created_at <= ?
    group by time, state
    order by time, state asc

**Comment by alexanderzobnin** [comment]
@sybrandy @jodok can you also tell which Grafana version do you use?

**Comment by jodok** [comment]
i'm using Grafana v4.1.2 (commit: v4.1.2)

**Comment by jodok** [comment]
i upgraded to v4.2.0 (commit: 349f3eb) and there the error disappears

**Comment by sybrandy** [comment]
I was using 4.1.1, but I upgraded to 4.2.0 and it's working for me now as well.  May I suggest that you add something to the README to document that users should use 4.2.0 for the current version of this plugin to prevent any further confusion?

Since it's working for me now, I'm going to close this.
