### ISSUE TITLE
 The datasource does not support alerting queries

### ISSUE THREAD

**Issue by taiuti** [raintank/crate-datasource#45]
If i define alert i have the following errors:

![schermata](https://cloud.githubusercontent.com/assets/1710430/25672248/0b358dfe-3033-11e7-9f92-1ad630804417.png)

**Comment by alexanderzobnin** [comment]
Crate data source doesn't support alerting now.

**Comment by jodok** [comment]
isn't this a grafana thing, where grafana periodically issues queries?

**Comment by torkelo** [comment]
@jodok yes but only a few core Grafana data source plugins support alerting as the data source code needs to be reimplmented and embedded in grafana backend for alerting to work for that data source. 

We hope to add backend plugins in the future so external data sources can support alerting but that is a long way way (and requires that data source be reimplemented in go)
