### ISSUE TITLE
400 error when pulling data

### ISSUE THREAD

**Issue by newengine** [raintank/crate-datasource#47]
here is the error that produce by the grafana dashboard

--- request
/api/datasources/proxy/1/_sql
Request Method:POST
Status Code:400 Bad Request

---response

{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No endpoint or operation is available at [_sql]"}],"type":"illegal_argument_exception","reason":"No endpoint or operation is available at [_sql]"},"status":400}

**Comment by alexanderzobnin** [comment]
@newengine can you tell about your environment (Crate DB version, plugin version)?

**Comment by newengine** [comment]
crate db 2.1.5,   plugin 0.5.1
