### ISSUE TITLE
Switch between Aggregation and Raw Data

### ISSUE THREAD

**Issue by joemoe** [raintank/crate-datasource#9]
A Crate user who is testing Grafana with Crate wants to be able to automatically switch between having data aggregated and raw data.
So whenever the resolution is sow high that you need raw data => use raw data.
Whenever Grafana isn't able to show all the Data points anyhow => aggregate in Crate.

I think the elasticsearch data source is doing something similar.

**Comment by alexanderzobnin** [comment]
@joemoe I think it's possible. Now you can use `Auto` Group By Time Interval, but not sure that it's what you need.

**Comment by joemoe** [comment]
@alexanderzobnin thanks, i will check this.

**Comment by joemoe** [comment]
@alexanderzobnin
at the moment it changes the first `date_trunc` parameter to `minute`, `second`,... and so on.
what we are looking for is something like this:
```sql
SELECT date_trunc('second', ts) as time, ...
```
to
```sql
SELECT ts as time,...
```
Because when using `date_trunc` we are not able to get to the original data.

**Comment by alexanderzobnin** [comment]
@joemoe I've added `Raw` agg type, which mean "No aggregation" for explicit raw data usage. Next step is auto usage raw data when it's possible.

**Comment by joemoe** [comment]
ok, will test that.

**Comment by jodok** [comment]
@joemoe have you been able to test? would be great if we can get this into the first beta release as well.

**Comment by joemoe** [comment]
@alexanderzobnin @jodok yes. it works fine to get the raw data now.
here are some things i'd like to improve:

* with raw data like we have here it is possible to zoom in so that there are no time labels anymore
<img width="1220" alt="bildschirmfoto 2016-09-23 um 10 04 23" src="https://cloud.githubusercontent.com/assets/68620/18778620/71249e38-8175-11e6-96f0-effc6dbd327e.png">

* When you chose raw data, it is still possible to include to set the integration interval, witch then wouldn't make any sense no more.

**Comment by joemoe** [comment]
when i think about it i don't know if the aggregation select field is the right place.

in my opinion this should be more part of the group by time interval logic.

group by "none" => raw.
auto => when showing only a few seconds it switches automatically to raw.

**Comment by alexanderzobnin** [comment]
@joemoe yes, it makes sense.

**Comment by joemoe** [comment]
@alexanderzobnin what do you mean? 
"yes, it makes sense what i said" or "yes, it makes sense where it is."
